### ISSUE TITLE
lxml is a requirement

### ISSUE THREAD

**Issue by seanroark** [zachpanz88/mlbgame#1]
[lxml ](https://pypi.python.org/pypi/lxml)needs to be installed. It is not installed by default for Windows at least.

**Comment by zachpanz88** [comment]
Thanks for noticing this. I did not realize that lxml was not installed by default. This issue is fixed in [Version 1.0.2](https://github.com/zachpanz88/mlbgame/releases/tag/v1.0.2) with commit https://github.com/zachpanz88/mlbgame/commit/9aba8f09cbe5f639f3cd59611c799a6e4bf648ff
