### ISSUE TITLE
Pitcher stat - Innings Pitched

### ISSUE THREAD

**Issue by illonks** [zachpanz88/mlbgame#10]
Hi, is there a way to get innings pitched using this library? It looks like the xml data that you get doesn't even contain this data?

**Comment by zachpanz88** [comment]
The data provided actually includes the outs that a pitcher has recorded in the game (property named `out`). You can divide this number by 3 to find the number of innings pitched, as full innings will divide evenly and others will be divided into thirds, which is the most common way of measuring partial innings pitched.
