### ISSUE TITLE
Probable starting pitcher

### ISSUE THREAD

**Issue by FlowFX** [zachpanz88/mlbgame#11]
This project is awesome. Thank you so much!

Is there a way to find the probable starting pitcher for today's games? They are displayed on mlb gameday.

**Comment by zachpanz88** [comment]
I'm not sure right now, but I will look into it and get back to you soon.

**Comment by zachpanz88** [comment]
After looking into it a little more, the file changes too much during the game and after the game so it can't be used in mlbgame. If you want to get this data on your own, it is available in linescore.xml for a game that has not been played yet. 

Here is an example (just change the date and game id to match):
http://gd2.mlb.com/components/game/mlb/year_2016/month_06/day_30/gid_2016_06_30_lanmlb_milmlb_1/linescore.xml

Alternatively, if you find a good solution for getting this data and submit it in a PR, I would be happy to merge it.

**Comment by FlowFX** [comment]
Thanks for the info! linescore.xml looks good. Probable starting pitcher is really only useful before the game starts. No need to put it into the mlbgame data. I'll have a PR for you, eventually. But it will take a while before I get to that part of my project.

For past games the starting pitcher is always the first pitcher in the pitching stats for that game, correct?

**Comment by zachpanz88** [comment]
Yes, they are in order of which they appeared in the game so the starter is first.

**Comment by FlowFX** [comment]
I just saw that the probable starting pitchers are now available. Thank you!! :D
