### ISSUE TITLE
Venue

### ISSUE THREAD

**Issue by rationalpastime** [zachpanz88/mlbgame#13]
Any chance that future updates will parse the venue value from linescore.xml?

Of course, 99% of the time, the venue is just the home team's park, but having venue data would help sort out games like last Sunday's Marlins-Braves contest at Fort Bragg, and the occasional overseas/Puerto Rico contests.

In my case, I use (your excellent) mlbgame in a workflow that includes park adjustments for player stats and home field adjustments for win expectancies. Being able to capture the venue would help ensure that I'm not correcting for park or home field factors that don't apply.

**Comment by zachpanz88** [comment]
First, that's awesome that you are using this API in a workflow! I will work on parsing the venue and will send out a release sometime within a week or two.

**Comment by zachpanz88** [comment]
Just checked out www.rationalpastime.com, it looks really awesome! I will be consistently checking it throughout the season. Great use of the API!

**Comment by rationalpastime** [comment]
Much appreciated. I was planning on using the package for some time, but
when my kid was born and I no longer had time to manually input the data
into excel every morning, I decided I had to buckle down and go all Python
on that bad boy.

**Comment by zachpanz88** [comment]
I have finished implementing this feature in e863b95d309d3b36c19fad3db52875cd5eae297d. I will release a new version later today/tonight (2.2).

**Comment by zachpanz88** [comment]
Just released the new version, feel free to update. The new overview function is what you will be looking for. Hopefully it works for what you need.

**Comment by rationalpastime** [comment]
Awesome. Thank you for this.
