### ISSUE TITLE
Issues with getting teams and differentiation

### ISSUE THREAD

**Issue by zenverak** [zachpanz88/mlbgame#16]
So far this is excellent but I don't see an easy way to do a few things

1. Get a list of active teams in the league. Something like   teams = mlbgame.teams
2. Differentiate between regular season and preseason games without specifying exact dates. Right now all  game.game_type show is 'go_game' .  This may be an issue with the source data.

Is this something I am missing?

**Comment by zachpanz88** [comment]
1. I am not sure that I can dynamically update that from mlb.com, but I can try to see if there is a way to implement all the teams as a list
2. If the games show up as go_game, that is the information that I receive from mlb.com. I am currently refactoring the game code and seeing if there is extra information that I can pull from mlb.com

**Comment by zachpanz88** [comment]
Update: It looks like I am able to get team data from mlb.com and I will work on implementing that into the api: http://mlb.mlb.com/properties/mlb_properties.xml

**Comment by zenverak** [comment]
Thanks man. I greatly appreciate it. So far I am enjoying using it as its extremely similar to nflgame so once I get the data in the format I want, I can use my existing code.

**Comment by zachpanz88** [comment]
Awesome, I designed this library after nflgame, which I had used in one of my own projects.

**Comment by zenverak** [comment]
Yeah, thats one of the main things I noticed.  In the end I am trying to find something like this for all of the sports so that I can get the data into a form I want so that I can do some 'analysis' on it. Right now its not anything statistical, but once I get more sports in I think I'll try and branch it into something that has some 'prediction power'.

**Comment by zachpanz88** [comment]
I have added this functionality in the dev branch. Feel free to clone that and test it out. This functionality will officially be released in the next release (probably 2.3.0) which will be coming out very soon.
