### ISSUE TITLE
Game Events Error

### ISSUE THREAD

**Issue by CandyOates** [zachpanz88/mlbgame#19]
Hi zachpanz88,

This is a very nice API. However, I notice that in events.game_events you have an error which causes the bottom of the inning to save the values for the top of the inning.

        # loop through the bottom half
        bot = x.findall('bottom')[0]
        for y in bot.findall('atbat'):
            # top info
            botinfo = []
            # loop through the top half
            bot = x.findall('top')[0]
            for y in bot.findall('atbat'):

**Comment by zachpanz88** [comment]
Yes, I think I lazily copied and pasted code from the top of the inning but forgot to change some values. I will fix this very soon.
