### ISSUE TITLE
Player Info

### ISSUE THREAD

**Issue by CandyOates** [zachpanz88/mlbgame#20]
Hi zachpanz88,

Is there a way to get basic information on the players through mlbgame?

For example, I have the player's id number, can I do something like mlbgame.player_info(player_id) to get a dict(Name="Cal Ripken", Throws="R", Bats="R", Team="Orioles").

Aside from this, the module leaves nothing to be desired :)

Thanks,
Andrew

**Comment by zachpanz88** [comment]
@CandyOates I'm glad you like the library. As for player information, I have looked briefly for a way to get that information in the past, but I will search again now. I agree that it would be very useful to have the information on a player, and mlb.com must have this data stored somewhere (not sure if public) so there is a good chance I will be able to implement this feature.

**Comment by zachpanz88** [comment]
I've done some searching and I am unable to find player information from the same source that I get the rest of the information (http://gd2.mlb.com/components/game/mlb/). It appears that each player is assigned to a different id for each game they play, and that id is only useful for getting stats for that single game.

So it looks like I will not be able to add this as a feature. If I notice anything that I can work with in the future I will be sure to add this feature.
