### ISSUE TITLE
Weather?

### ISSUE THREAD

**Issue by CandyOates** [zachpanz88/mlbgame#21]
Also, any chance there is basic weather information for the games?

**Comment by zachpanz88** [comment]
Not sure if there is any weather information but I will look.

**Comment by zachpanz88** [comment]
Unfortunately I have not been able to find any information on the weather for games.

However, I think that there could be a little workaround: Since mlbgame provides the date, time, and location of the game, you could use a different weather api to retrieve weather information at that time.
