### ISSUE TITLE
mlbgame, python, django

### ISSUE THREAD

**Issue by noelvillaman** [zachpanz88/mlbgame#22]
I am using mlbgame for python and I am getting some data that I do not now how to manipulate. Can you direct me to the right track please. 

Here is my view on Python, Django.

import mlbgame

def baseball(request):
games1 = mlbgame.day(2017, 8, 10)
angels_game = mlbgame.games(2017, home='Angels', away='Angels')
return render(request, 'home/baseball.html', {'games1': games1, 'angels_game': angels_game})

Here is my template

<h1>Anaheim Angels Games</h1>
{% for anaheim in angels_game %}
<p>{{ anaheim }}</p>
{% endfor %}

I am getting many like this : mlbgame.game.GameScoreboard object at 0x7f04f2f0ac50.

Is there a way to do something like mlbgame.game.GameScoreboard object at 0x7f04f2f0ac50.GETGAMEDAY()?

I know I am printing the object here, but I do not know the attributes of that object.

Thanks,

Noel.

**Comment by zachpanz88** [comment]
@noelvillaman If you want to find out the attributes of the first game in the `angels_game` object, you can use `__dict__` to print a dictionary of the object properties: `print angels_game[0].__dict__`

**Comment by zachpanz88** [comment]
In addition, all of the documentation along with the project code can be accessed at http://panz.io/mlbgame

**Comment by noelvillaman** [comment]
Thanks,

My problem was solved. Now I would like to find the dates where there is not game. For example, 
for game in games:
     if game.date.day == "No return, i do not know how to put it"
          Here, I would like to do something with a td. I am just replicating the schedule of the http://losangeles.angels.mlb.com/schedule/index.jsp?c_id=ana#y=2017&m=4&calendar=DEFAULT

I have a bunch of <td> where I put the info coming from each game, but is there is not game i would like to add a class to that <td>. Is there a function like game.notgametoday or so?

Do you understand?

Thanks for your help.

Noel.
