### ISSUE TITLE
handle boxscores with 'ig_game' tag

### ISSUE THREAD

**Issue by kajensen** [zachpanz88/mlbgame#3]
What is the reason for not handling games with tag 'ig_game' (i'm assuming this means "in-game"?)? I've hacked a solution for it but the data is not exactly the same as a 'go_game' ("game-over"?). I think this needs to be implemented in order for the library to update in real-time.

**Comment by zachpanz88** [comment]
When I originally made this program, the season had just ended and therefore no games were being played. Now that spring training has started up again, I will look into `ig_game`. Thanks for the info

**Comment by zachpanz88** [comment]
Fixed with commit 29b5c0362fa2a674dbb9fc649a3466d1c9e6e5e7, thanks.

**Comment by zachpanz88** [comment]
Added in [version 2.0.0](https://github.com/zachpanz88/mlbgame/releases/tag/v2.0.0), please update mlbgame to receive the changes

**Comment by kajensen** [comment]
Awesome! Thanks for the quick response/fix
