### ISSUE TITLE
Accessing the local mlbgame database directly

### ISSUE THREAD

**Issue by tmthyjames** [zachpanz88/mlbgame#4]
How can i directly access the database instead of using the python module?

**Comment by zachpanz88** [comment]
I'm not quite sure exactly what you are asking, but the local game data is stored in `mlbgame/gameday-data` and the remote data from mlb.com can be accessed here: http://gd2.mlb.com/components/game/mlb/. The data is not stored in a database, but rather as compressed XML files, and the data provided by mlb.com are XML files.
