### ISSUE TITLE
player_stats & team_stats don't always return obp, ops and slg

### ISSUE THREAD

**Issue by tmthyjames** [zachpanz88/mlbgame#5]
obp, ops and slg aren't always returned for `player_stats()` and `team_stats()` even though `idmap['obp']['always']`, `idmap['ops']['always']` and `idmap['slg']['always']` are set to `True`. 

Example: `mlbgame.stats.team_stats('2015_04_01_bosmlb_minmlb_1')`

returns

```{'away_batting': {'ab': '32',
  'avg': '.285',
  'bb': '6',
  'd': '1',
  'da': '8',
  'h': '7',
  'hr': '0',
  'lob': '16',
  'po': '27',
  'r': '4',
  'rbi': '3',
  'so': '6',
  't': '0',
  'team_flag': 'away'},
 'away_pitching': {'bb': '5',
  'bf': '45',
  'er': '4',
  'era': '4.40',
  'h': '13',
  'hr': '1',
  'out': '27',
  'r': '4',
  'so': '8',
  'team_flag': 'away'},
 'home_batting': {'ab': '40',
  'avg': '.258',
  'bb': '5',
  'd': '1',
  'da': '7',
  'h': '13',
  'hr': '1',
  'lob': '26',
  'po': '27',
  'r': '4',
  'rbi': '4',
  'so': '8',
  't': '0',
  'team_flag': 'home'},
 'home_pitching': {'bb': '6',
  'bf': '39',
  'er': '4',
  'era': '3.87',
  'h': '7',
  'hr': '0',
  'out': '27',
  'r': '4',
  'so': '6',
  'team_flag': 'home'}}````

**Comment by tmthyjames** [comment]
I can calculate obp from other stats, but not slg or ops (unless there is data for singles, doubles and triples which I haven't been able to find). 

Is it possible to get single, double, triple data per game?

**Comment by zachpanz88** [comment]
That's odd, ops and slg do not appear to show up on spring training games. That's on MLB, there's nothing I can really do if they do not provide the data. As far as I know, data for individual types of hits is not provided but there is a list of all the events that occurred in the game, and you could go through and see who was batting for each event and what the outcome was. Here is the list of events for the game that you gave an example of: http://gd2.mlb.com/components/game/mlb/year_2015/month_04/day_01/gid_2015_04_01_bosmlb_minmlb_1/game_events.xml. I'll continue to look into the issue with slg and ops.

**Comment by tmthyjames** [comment]
Got it. Thanks for the game events link; I can scrape through that to find 1b, 2b and 3b data.

Will there be support in the future for getting play-by-play events through mlbgame? Wasn't sure if it was already in the works.

**Comment by zachpanz88** [comment]
I'm thinking about it, not exactly sure how I'm going to add it to the project but it will probably be coming soon along with other feature additions.

**Comment by rationalpastime** [comment]
Double and triple data are there. The stats are labeled 'd' and 't'. You can get slg via (h + d + 2*t + 3hr)/ab.

**Comment by zachpanz88** [comment]
Thanks @rationalpastime. Updated statmap with commit f76408e86ef365bb95466d9f15c2294c280dbf6c, new release coming sometime soon.
