### ISSUE TITLE
Players Ids

### ISSUE THREAD

**Issue by ma-rp** [zachpanz88/mlbgame#7]
Hello,

Thank you very much for this initiative.

Is it possible to include player's ids?
That way you can use the data returned with other data sources.

For example something like this would be useful:
games = mlbgame.games(2015, 4)
for day in games :
  for g in day:
    print(g.w_pitcher_id)

Thank you in advance for your help.

**Comment by zachpanz88** [comment]
Unfortunately, mlb.com does not provide the player's ID in `mlbgame.games()`. However, you could get the game ID and use that to get the stats for that game, which will provide the full stats for the winning pitcher. Here is a simple hack to print the winning pitcher's IDs for your scenario:

```python
for day in games:
    for g in day:
        try:
            stats = mlbgame.player_stats(g.game_id)
            for p in stats['home_pitching']:
                if hasattr(p, 'win') and p.win:
                    print p.id
            for p in stats['away_pitching']:
                if hasattr(p, 'win') and p.win:
                    print p.id
        except:
            pass
```

**Comment by ma-rp** [comment]
Thank you for that example!
I can work with something similar from your post.

Thank you very much.

**Comment by zachpanz88** [comment]
No problem. I'm happy to help.
