### ISSUE TITLE
Cannot pip install mlbgame

### ISSUE THREAD

**Issue by DaltheCow** [zachpanz88/mlbgame#9]
"error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/docs': Permission denied

and after that message, it prints:

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/7t/2vyvr6056v553r15xpx0gjl00000gn/T/pip-build-Y2rvAh/mlbgame/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/7t/2vyvr6056v553r15xpx0gjl00000gn/T/pip-5ibLS1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/7t/2vyvr6056v553r15xpx0gjl00000gn/T/pip-build-Y2rvAh/mlbgame/

I've tried all sorts of work arounds and can't figure out why that error won't stop

**Comment by zachpanz88** [comment]
Try `sudo pip install mlbgame`. If you can't install with pip, you can always download a zip [here](https://github.com/zachpanz88/mlbgame/releases).

**Comment by DaltheCow** [comment]
I swear I tried that already and it didn't work but I tried it again and it
worked, thanks!
